service: image-analysis
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  iamRoleStatements: 
    - Effect: "Allow"
      Action:
        - rekognition:DetectLabels
      Resource: "*"
    - Effect: "Allow"
      Action:
        - translate:TranslateText
      Resource: "*"

functions:
  img-analysis: #esse e o cara que eu tenho que chamar na função pelo cli
    handler: index.main
    events:
      - http:
          path: analyse
          method: get
